# Generated by Django 4.2.3 on 2023-07-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=1000)),
                ('origin', models.CharField(max_length=1000)),
                ('destination', models.CharField(max_length=1000)),
            ],
        ),
    ]
