# Generated by Django 4.2.3 on 2023-07-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_alter_tour_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='date',
        ),
    ]
